version: "3.3"
services:
  oda-cc-BookingFormData:
    build: .
    image: "oda-cc-BookingFormData:1.0"
    container_name: "oda-cc-BookingFormData"
    command: "npm start"
    ports:
      - 3000:3000    